steps:
  # Стъпка 1: Изграждане на Docker изображението
  # Използваме таг с commit SHA за проследимост на версиите
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'europe-north1-docker.pkg.dev/$PROJECT_ID/bg-cycling-plan/bg-cycling-app:$COMMIT_SHA'
      - '.'

  # Стъпка 2: Изпращане на изображението в Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'europe-north1-docker.pkg.dev/$PROJECT_ID/bg-cycling-plan/bg-cycling-app:$COMMIT_SHA'

  # Стъпка 3: Разгръщане в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bg-cycling-service'
      - '--image'
      - 'europe-north1-docker.pkg.dev/$PROJECT_ID/bg-cycling-plan/bg-cycling-app:$COMMIT_SHA'
      - '--region'
      - 'europe-north1'
      - '--allow-unauthenticated' # Прави сайта публично достъпен
      - '--port'
      - '8080'

# Добавяме изображенията в списъка за проследяване от Cloud Build
images:
  - 'europe-north1-docker.pkg.dev/$PROJECT_ID/bg-cycling-plan/bg-cycling-app:$COMMIT_SHA'
